### ISSUE TITLE
Empty instance method should not be printed

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#151] opened 2017-06-09 23:08 UTC
```ruby
 class Foo
   def bar
   end
 end

 a = Foo.new
 puts(a.bar)
```

* Goby: `<Instance of: Foo>`
* Ruby: empty line

**Comment by st0012** [comment] 2017-06-10 01:21
The cause is that empty instance method returns the instance itself, investigating.

**Comment by st0012** [comment] 2017-06-11 02:44
Should be fixed in https://github.com/goby-lang/goby/commit/3834168f16102d7a57e1d508b4eb292b1cd0da08

**Comment by hachi8833** [comment] 2017-06-11 05:55
Confirmed the bug has been fixed!

**Closed** 2017-06-11 06:47 UTC
Labels: 3 - Review, bug
